name: Scan for leaked credentials

on:
    push:
    pull_request:

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: TruffleHog OSS
              uses: trufflesecurity/trufflehog@v3.93.8

            # - name: Test for public javascript library vulnerabilities
            #   uses: lirantal/is-website-vulnerable@main
            #   with:
            #       scan-url: "https://yoursite.com"
